FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cpio \
    wget \
    bzip2

ENV BUSYBOX_VERSION 1.36.1
RUN wget -O busybox-${BUSYBOX_VERSION}.tar.bz2 https://www.busybox.net/downloads/busybox-1.36.1.tar.bz2 && \
    mkdir -p /usr/src/busybox && \
    tar -xvjf ./busybox-${BUSYBOX_VERSION}.tar.bz2 -C /usr/src/busybox/ --strip-components=1 && \
    rm ./busybox.tar.bz2

WORKDIR /usr/src/busybox/

RUN make defconfig && \
    sed -i 's/^.*CONFIG_STATIC[^_].*$/CONFIG_STATIC=y/g' ./.config && \
    make -j2 CC="musl-gcc -static" busybox


