version: "3.8"
services:
  busybox:
    build:
      context: "."
      dockerfile: "./utils/busybox/Dockerfile"
      tags:
        - "bubo_builder:01"
    stop_signal: SIGINT
  kernel:
    build:
      context: "./utils/kernel/"
    stop_signal: SIGINT
