version: "3.8"
services:
  busybox:
    build:
      context: "."
      dockerfile: "./utils/busybox/Dockerfile"
      #dockerfile: "./utils/busybox/Dockerfile.bubo_debug"
      #dockerfile: "./utils/busybox/Dockerfile.muslrust"
      tags:
        - "localhost:5000/bubo_builder:latest"
        #- "bubo_builder:02"
        #- "debian_deps:01"
        #- "bubo_debug:01"
        #- "muslrust:01"
    stop_signal: SIGINT
  kernel:
    build:
      context: "./utils/kernel/"
      tags:
        - "localhost:5000/linux_build:latest"
    stop_signal: SIGINT
