
name: Compile Busybox and and generate an initramfs

# This rule triggers when the workflow will run
on:
  # run the workflow manually from Actions tab
  workflow_dispatch:

# jobs can run in sequence or parallel in a workflow
jobs:
  # This single job is called "build"
  build:
    # Specify the operating system for the runner job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # the job gets runned into $GITHUB_WORKSPACE, that is the environment variable for the repo
      - name: Access current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build docker image
        run: |
          make build_bubo
          #source ./scripts/ccr.sh; checker
          #docker compose -f ./compose.yml build busybox
          #docker build -t bubo-builder -f="./utils/kernel/Dockerfile"


      - name: Retrieve artifact from docker image
        run: |
          #docker run -it --name bubo -d bubo-builder:latest
          docker run -it --name bubo -d eulab-poc-busybox:latest
          docker cp bubo:./bubo.tar.gz ${{ github.workspace }}/artifacts/bubobins/

      - name: Archive the build artifact
        uses: actions/upload-artifact@v3
        with:
          name: bubo
          # image size: 67.3MB
          # artifact size: 12.9M
          path: ${{ github.workspace }}/artifacts/bubobins/bubo.tar.gz

