
name: Generate ramdisk

# This rule triggers when the workflow will run
on:
  # run the workflow manually from Actions tab
  workflow_dispatch:

# jobs can run in sequence or parallel in a workflow
jobs:
  # This single job is called "build"
  build:
    # Specify the operating system for the runner job
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # the job gets runned into $GITHUB_WORKSPACE, that is the environment variable for the repo
      - name: Access current repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Build docker image
        run: |
          docker compose -f ./compose.yml --progress=plain build busybox
          #podman build -t bubo_builder:latest -f ./utils/busybox/Dockerfile


      - name: Retrieve artifact from docker image
        run: |
          podman run -it --name bubo -d bubo_builder:latest
          podman cp bubo:./initramfs.cpio.gz ${{ github.workspace }}/artifacts/

      - name: Archive the build artifact
        uses: actions/upload-artifact@v3
        with:
          name: bubo
          # image size: 8.48MB
          # artifact size: 829.6K
          path: ${{ github.workspace }}/artifacts/initramfs.cpio.gz

